"""create inital tables

Revision ID: 8f49ec2c100f
Revises: 
Create Date: 2022-04-17 07:53:41.636399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '8f49ec2c100f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_tax_category_code', sa.String(length=255), nullable=True),
    sa.Column('commodity_tax_category_name', sa.String(length=255), nullable=True),
    sa.Column('goods_code', sa.String(length=255), nullable=True),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.Column('goods_tax_id', sa.String(length=255), nullable=True),
    sa.Column('is_exempt', sa.String(length=255), nullable=True),
    sa.Column('is_zero_rate', sa.String(length=255), nullable=True),
    sa.Column('measure_unit', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('unit_price', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'SENDING', 'SENT', 'ERROR', name='invoicestatuses'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_client_id'), 'stock', ['client_id'], unique=False)
    op.create_index(op.f('ix_stock_commodity_tax_category_code'), 'stock', ['commodity_tax_category_code'], unique=False)
    op.create_index(op.f('ix_stock_commodity_tax_category_name'), 'stock', ['commodity_tax_category_name'], unique=False)
    op.create_index(op.f('ix_stock_currency'), 'stock', ['currency'], unique=False)
    op.create_index(op.f('ix_stock_goods_code'), 'stock', ['goods_code'], unique=False)
    op.create_index(op.f('ix_stock_goods_name'), 'stock', ['goods_name'], unique=False)
    op.create_index(op.f('ix_stock_goods_tax_id'), 'stock', ['goods_tax_id'], unique=False)
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    op.create_index(op.f('ix_stock_is_exempt'), 'stock', ['is_exempt'], unique=False)
    op.create_index(op.f('ix_stock_is_zero_rate'), 'stock', ['is_zero_rate'], unique=False)
    op.create_index(op.f('ix_stock_measure_unit'), 'stock', ['measure_unit'], unique=False)
    op.create_index(op.f('ix_stock_remarks'), 'stock', ['remarks'], unique=False)
    op.create_index(op.f('ix_stock_tax_rate'), 'stock', ['tax_rate'], unique=False)
    op.create_index(op.f('ix_stock_unit_price'), 'stock', ['unit_price'], unique=False)
    op.create_table('stock_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_branches_client_id'), 'stock_branches', ['client_id'], unique=False)
    op.create_index(op.f('ix_stock_branches_id'), 'stock_branches', ['id'], unique=False)
    op.create_table('tax_invoice_outgoing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_code', sa.String(length=255), nullable=True),
    sa.Column('instance_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('client_tin', sa.String(length=255), nullable=True),
    sa.Column('related_invoice', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('upload_code', sa.String(length=255), nullable=True),
    sa.Column('upload_desc', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'SENDING', 'SENT', 'ERROR', name='invoicestatuses'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_invoice_outgoing_client_tin'), 'tax_invoice_outgoing', ['client_tin'], unique=False)
    op.create_index(op.f('ix_tax_invoice_outgoing_id'), 'tax_invoice_outgoing', ['id'], unique=False)
    op.create_index(op.f('ix_tax_invoice_outgoing_instance_invoice_id'), 'tax_invoice_outgoing', ['instance_invoice_id'], unique=True)
    op.create_index(op.f('ix_tax_invoice_outgoing_invoice_code'), 'tax_invoice_outgoing', ['invoice_code'], unique=False)
    op.create_index(op.f('ix_tax_invoice_outgoing_related_invoice'), 'tax_invoice_outgoing', ['related_invoice'], unique=False)
    op.create_index(op.f('ix_tax_invoice_outgoing_upload_code'), 'tax_invoice_outgoing', ['upload_code'], unique=False)
    op.create_table('tax_invoice_numbers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_code', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('number_begin', sa.String(length=255), nullable=True),
    sa.Column('number_end', sa.String(length=255), nullable=True),
    sa.Column('instance_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_invoice_id'], ['tax_invoice_outgoing.instance_invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_invoice_numbers_date_added'), 'tax_invoice_numbers', ['date_added'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_id'), 'tax_invoice_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_invoice_code'), 'tax_invoice_numbers', ['invoice_code'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_invoice_number'), 'tax_invoice_numbers', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_number_begin'), 'tax_invoice_numbers', ['number_begin'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_number_end'), 'tax_invoice_numbers', ['number_end'], unique=False)
    op.create_index(op.f('ix_tax_invoice_numbers_tax_id'), 'tax_invoice_numbers', ['tax_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_invoice_numbers_tax_id'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_number_end'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_number_begin'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_invoice_number'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_invoice_code'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_id'), table_name='tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_numbers_date_added'), table_name='tax_invoice_numbers')
    op.drop_table('tax_invoice_numbers')
    op.drop_index(op.f('ix_tax_invoice_outgoing_upload_code'), table_name='tax_invoice_outgoing')
    op.drop_index(op.f('ix_tax_invoice_outgoing_related_invoice'), table_name='tax_invoice_outgoing')
    op.drop_index(op.f('ix_tax_invoice_outgoing_invoice_code'), table_name='tax_invoice_outgoing')
    op.drop_index(op.f('ix_tax_invoice_outgoing_instance_invoice_id'), table_name='tax_invoice_outgoing')
    op.drop_index(op.f('ix_tax_invoice_outgoing_id'), table_name='tax_invoice_outgoing')
    op.drop_index(op.f('ix_tax_invoice_outgoing_client_tin'), table_name='tax_invoice_outgoing')
    op.drop_table('tax_invoice_outgoing')
    op.drop_index(op.f('ix_stock_branches_id'), table_name='stock_branches')
    op.drop_index(op.f('ix_stock_branches_client_id'), table_name='stock_branches')
    op.drop_table('stock_branches')
    op.drop_index(op.f('ix_stock_unit_price'), table_name='stock')
    op.drop_index(op.f('ix_stock_tax_rate'), table_name='stock')
    op.drop_index(op.f('ix_stock_remarks'), table_name='stock')
    op.drop_index(op.f('ix_stock_measure_unit'), table_name='stock')
    op.drop_index(op.f('ix_stock_is_zero_rate'), table_name='stock')
    op.drop_index(op.f('ix_stock_is_exempt'), table_name='stock')
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_goods_tax_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_goods_name'), table_name='stock')
    op.drop_index(op.f('ix_stock_goods_code'), table_name='stock')
    op.drop_index(op.f('ix_stock_currency'), table_name='stock')
    op.drop_index(op.f('ix_stock_commodity_tax_category_name'), table_name='stock')
    op.drop_index(op.f('ix_stock_commodity_tax_category_code'), table_name='stock')
    op.drop_index(op.f('ix_stock_client_id'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###

